<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ieris19.lib.util</groupId>
        <artifactId>utils</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>command-console</artifactId>
    <version>1.0.0</version>

    <dependencies>
        <dependency>
            <groupId>com.ieris19.lib</groupId>
            <artifactId>commons</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <name>Command Console</name>
    <description>A tool that takes over a shell in order to provide easy command parsing from a Java application</description>
    <url>${ieris.source.repoURL}/utils/console</url>
    <inceptionYear>2021</inceptionYear>
</project>