<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ieris19.lib.util.log</groupId>
        <artifactId>ierislog-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ierislog-custom</artifactId>
    <version>1.0.0</version>

    <name>Customizable Logger</name>
    <description>An implementation that allows for customization of the logger through the use of tiny scripts</description>
    <url>${ieris.source.repoURL}/ierislog-custom</url>
    <inceptionYear>2022</inceptionYear>

    <dependencies>
        <dependency>
            <groupId>com.ieris19.lib.util.log</groupId>
            <artifactId>ierislog-core</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>