<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ieris19.lib</groupId>
        <artifactId>ierislib</artifactId>
        <version>2.1.1</version>
    </parent>

    <modules>
        <module>cards</module>
        <module>dice</module>
    </modules>

    <groupId>com.ieris19.lib.games</groupId>
    <artifactId>games</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Game Tools</name>
    <description>A library of reusable Java code that implements simple common game tools</description>
    <url>${ieris.source.repoURL}</url>
    <inceptionYear>2021</inceptionYear>
</project>