<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ieris19.lib</groupId>
        <artifactId>ierislib</artifactId>
        <version>2.1.1</version>
    </parent>

    <groupId>com.ieris19.lib.ui</groupId>
    <artifactId>ierisfx</artifactId>
    <version>3.1.0</version>

    <name>IerisFX</name>
    <description>A framework to quickly scaffold JavaFX applications</description>
    <url>${ieris.source.repoURL}/ierisfx</url>
    <inceptionYear>2021</inceptionYear>

    <properties>
        <ieris.java.version>21</ieris.java.version>
        <ieris.dependencyVersion.javafx>21</ieris.dependencyVersion.javafx>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${ieris.dependencyVersion.javafx}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.12</version>
        </dependency>
        <dependency>
            <groupId>com.ieris19.lib</groupId>
            <artifactId>commons</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.ieris19.lib.files</groupId>
            <artifactId>config-manager</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
</project>