<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ieris19.lib.util</groupId>
        <artifactId>utils</artifactId>
        <version>1.0.0</version>
    </parent>

    <modules>
        <module>ierislog-custom</module>
        <module>ierislog-slf4j</module>
        <module>ierislog-core</module>
    </modules>

    <groupId>com.ieris19.lib.util.log</groupId>
    <artifactId>ierislog-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Logging Framework</name>
    <description>An extensive framework that allows for logging in many ways</description>
    <url>${ieris.source.repoURL}/ierislog-parent</url>
    <inceptionYear>2023</inceptionYear>

    <dependencies>
        <dependency>
            <groupId>com.ieris19.lib</groupId>
            <artifactId>commons</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>