<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>ierislib</artifactId>
        <groupId>com.ieris19.lib</groupId>
        <version>2.1.1</version>
    </parent>

    <groupId>com.ieris19.lib.util</groupId>
    <artifactId>utils</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>command-console</module>
        <module>scoreboard</module>
        <module>ierislog-parent</module>
    </modules>

    <name>Utilities Library</name>
    <description>A parent artifact for all classes that provide utilities</description>
    <url>${ieris.source.repoURL}/utils</url>
    <inceptionYear>2022</inceptionYear>
</project>