<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>ierislib</artifactId>
        <groupId>com.ieris19.lib</groupId>
        <version>2.1.1</version>
    </parent>

    <groupId>com.ieris19.lib.reflection</groupId>
    <artifactId>reflection</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>reflection-utils</module>
    </modules>

    <name>Reflective Library</name>
    <description>A specialized module focused on interactions with the Reflection API in Java</description>
    <url>${ieris.source.repoURL}/reflection</url>
    <inceptionYear>2022</inceptionYear>
</project>